language: c
before_install:
  - sudo apt-get update && sudo apt-get install -y racket
script:
  - raco test tests
after_success:
  - raco pkg install --deps search-auto cover cover-codecov
  - raco cover -f codecov tests
