language: c
sudo: false
env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=7.0
    - RACKET_VERSION=7.1
    - RACKET_VERSION=7.2
    - RACKET_VERSION=7.3
    - RACKET_VERSION=7.4
    - RACKET_VERSION=7.5
    - RACKET_VERSION=RELEASE
before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"
script:
  - make compile
  - make test
after_success:
  - raco pkg install --deps search-auto cover cover-codecov
  - raco cover -f codecov -b tests .
