language: c

before_install:
  - apt-get update && apt-get install -y racket

install: raco pkg install --deps search-auto $TRAVIS_BUILD_DIR

script:
  - raco test $TRAVIS_BUILD_DIR

after_success:
  - raco pkg install --deps search-auto cover cover-codecov
  - raco cover -f codecov -d $TRAVIS_BUILD_DIR/coverage . 