version: 2
jobs:
  build:
    working_directory: /temp
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -y racket make
      - run: make compile
      - run: make test
