version: 2
jobs:
  build:
    working_directory: /temp
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -y libssl-dev ca-certificates racket make
      - run: raco pkg install --batch --deps search-auto cover-codecov
      - run: make compile
      - run: make test
      - run: raco cover -f codecov -d tests/coverage -b tests
